-- 1. 生命力とライフサイクル (Life & Time)
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS vitality INTEGER DEFAULT 100;

-- 2. 精神と社会 (Mind & Society)
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS praise_count INTEGER DEFAULT 0;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS prayer_count INTEGER DEFAULT 0;

-- 3. 戦闘と成長 (Combat & Growth)
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS exp INTEGER DEFAULT 0;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS max_hp INTEGER DEFAULT 100;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS hp INTEGER DEFAULT 100;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS max_mp INTEGER DEFAULT 20;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS mp INTEGER DEFAULT 20;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS attack INTEGER DEFAULT 10;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS defense INTEGER DEFAULT 5;
