-- Create gossip_posts table
CREATE TABLE gossip_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    epithet TEXT,
    avatar_url TEXT,
    content VARCHAR(140) NOT NULL,
    location_id UUID REFERENCES locations(id) ON DELETE SET NULL,
    location_name TEXT,
    is_system BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Create index on created_at for fast paginated reads
CREATE INDEX gossip_posts_created_at_idx ON gossip_posts(created_at DESC);

-- Enable RLS
ALTER TABLE gossip_posts ENABLE ROW LEVEL SECURITY;

-- Select policy: authenticated users can read all posts
CREATE POLICY "Allow authenticated users to read posts" 
ON gossip_posts FOR SELECT 
TO authenticated 
USING (true);

-- Insert policy: users can insert their own posts (max 140 chars, no system posts spoofing)
CREATE POLICY "Allow users to insert their own posts" 
ON gossip_posts FOR INSERT 
TO authenticated 
WITH CHECK (
    auth.uid() = user_id 
    AND is_system = false 
    AND length(content) <= 140
);

-- Cleanup: drop obsolete rumors table
DROP TABLE IF EXISTS rumors CASCADE;
