-- 過去シーズンのアリーナ成績履歴テーブル
CREATE TABLE IF NOT EXISTS pvp_season_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id TEXT NOT NULL, -- 例: '2026-W28'
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    avatar_url TEXT,
    arena_rate INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- シーズン内のデイリーアリーナ成績履歴テーブル
CREATE TABLE IF NOT EXISTS pvp_daily_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_str TEXT NOT NULL, -- 例: '2026-07-09'
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    avatar_url TEXT,
    arena_rate INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pvp_season_history_user ON pvp_season_history(user_id);
CREATE INDEX IF NOT EXISTS idx_pvp_daily_history_user ON pvp_daily_history(user_id);

ALTER TABLE pvp_season_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE pvp_daily_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on pvp_season_history" ON pvp_season_history;
CREATE POLICY "Allow public select on pvp_season_history" ON pvp_season_history
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public select on pvp_daily_history" ON pvp_daily_history;
CREATE POLICY "Allow public select on pvp_daily_history" ON pvp_daily_history
    FOR SELECT USING (true);

-- デイリー履歴アーカイブ用RPC (レート1000以上の全アクティブユーザー対象)
CREATE OR REPLACE FUNCTION archive_pvp_daily_history(p_date_str text)
RETURNS void AS $$
BEGIN
    INSERT INTO pvp_daily_history (date_str, user_id, user_name, avatar_url, arena_rate, rank)
    SELECT 
        p_date_str,
        up.id,
        COALESCE(up.name, '名もなき旅人'),
        up.avatar_url,
        up.arena_rate,
        ROW_NUMBER() OVER (ORDER BY up.arena_rate DESC) as rank
    FROM user_profiles up
    WHERE up.arena_rate >= 1000
      AND up.id IN (SELECT id FROM auth.users);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- シーズン履歴アーカイブ用RPC (レート1000以上の全アクティブユーザー対象)
CREATE OR REPLACE FUNCTION archive_pvp_season_history(p_season_id text)
RETURNS void AS $$
BEGIN
    INSERT INTO pvp_season_history (season_id, user_id, user_name, avatar_url, arena_rate, rank)
    SELECT 
        p_season_id,
        up.id,
        COALESCE(up.name, '名もなき旅人'),
        up.avatar_url,
        up.arena_rate,
        ROW_NUMBER() OVER (ORDER BY up.arena_rate DESC) as rank
    FROM user_profiles up
    WHERE up.arena_rate >= 1000
      AND up.id IN (SELECT id FROM auth.users);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
