-- Force Recreation of Scenarios Table to include 'difficulty' column
-- This ensures the schema is updated even if the previous migration file was marked as applied.

DROP TABLE IF EXISTS scenarios CASCADE;

CREATE TABLE scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    client_name TEXT DEFAULT 'Unknown',
    
    -- V3 Quest System Fields
    type TEXT DEFAULT 'Subjugation',
    difficulty INTEGER DEFAULT 1, -- Added (Fix for missing column)
    time_cost INTEGER DEFAULT 1,
    ruling_nation_id TEXT, -- For filtering by nation
    location_id UUID REFERENCES locations(id), -- Specific location binding
    
    -- JSONB Logic
    conditions JSONB DEFAULT '{}'::jsonb,
    rewards JSONB DEFAULT '{}'::jsonb,
    flow_nodes JSONB DEFAULT '[]'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE scenarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read scenarios" ON scenarios FOR SELECT USING (true);
