-- Migration to support User Defined Integer IDs for Master Data

-- 1. Cards Table (New High Level Concept for Spec v6+)
CREATE TABLE IF NOT EXISTS cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'Skill',
    cost_type TEXT CHECK (cost_type IN ('vitality', 'mp')),
    cost_val INTEGER DEFAULT 0,
    effect_val INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read cards" ON cards FOR SELECT USING (true);


-- 2. Items Table (Recreate with Integer ID)
-- Drop existing foreign keys referencing items first if any
DROP TABLE IF EXISTS inventory CASCADE; -- Inventory references items.id
DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('consumable', 'skill', 'equipment')),
    base_price INTEGER DEFAULT 0,
    min_prosperity INTEGER DEFAULT 1,
    nation_tags TEXT[] DEFAULT '{}',
    linked_card_id BIGINT REFERENCES cards(id), -- For Skill items
    effect_data JSONB DEFAULT '{}'::jsonb, -- Keep JSONB for flexibility alongside linked_card
    is_black_market BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read items" ON items FOR SELECT USING (true);


-- 3. Party Members / NPCs (Recreate with Integer ID for Master)
--   Note: This table serves as BOTH Master (Template) and Instance?
--   User said "npcs.csv -> party_members".
--   If we use Integer PK, instances also need Integer PKs (Auto Inc).
--   Master entries will have specific IDs (e.g. 100).
--   Instances will be auto-generated (e.g. 10000+).

DROP TABLE IF EXISTS party_members CASCADE;

CREATE TABLE party_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES user_profiles(id), -- NULL for Template/Pool matches
    slug TEXT, -- NULL for Generic Instances? Or Template Slug?
    name TEXT NOT NULL,
    gender TEXT DEFAULT 'Unknown',
    job_class TEXT DEFAULT 'Civilian',
    
    -- Stats
    durability INTEGER DEFAULT 100,
    max_durability INTEGER DEFAULT 100,
    cover_rate INTEGER DEFAULT 0,
    loyalty INTEGER DEFAULT 50,
    
    -- Cards Deck
    inject_cards INTEGER[] DEFAULT '{}', -- References cards(id)
    
    -- Instance Flags
    is_active BOOLEAN DEFAULT TRUE,
    origin_type TEXT DEFAULT 'system', -- 'system', 'shadow_active', etc.
    source_user_id UUID REFERENCES user_profiles(id), -- For Shadows
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Constraint: Uniqueness of Slug Only for Templates (where owner_id is NULL)?
    -- Actually, if we use CSV to seed, we might reuse slugs for instances?
    -- No, usually slug is unique for the MASTER definition.
    -- We can add a Partial Index for unique slug where owner_id IS NULL.
    CONSTRAINT unique_slug_for_master UNIQUE (slug)
);

-- Enable RLS
ALTER TABLE party_members ENABLE ROW LEVEL SECURITY;
-- Owners see their own members. Everyone sees Pool members (owner_id NULL).
CREATE POLICY "Users see own and pool members" ON party_members 
    FOR SELECT USING (auth.uid() = owner_id OR owner_id IS NULL);


-- 4. Recreate Inventory (referencing new Items ID)
CREATE TABLE inventory (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES user_profiles(id),
    item_id BIGINT REFERENCES items(id),
    quantity INTEGER DEFAULT 1,
    is_equipped BOOLEAN DEFAULT FALSE,
    is_skill BOOLEAN DEFAULT FALSE,
    acquired_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own inventory" ON inventory
    FOR SELECT USING (auth.uid() = user_id);

-- 5. Scenarios / Quests (Recreate with Integer ID)
DROP TABLE IF EXISTS scenarios CASCADE;

CREATE TABLE scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    client_name TEXT DEFAULT 'Unknown',
    
    -- V3 Quest System Fields
    type TEXT DEFAULT 'Subjugation',
    difficulty INTEGER DEFAULT 1, -- Added from CSV
    time_cost INTEGER DEFAULT 1,
    ruling_nation_id TEXT, -- For filtering by nation
    location_id UUID REFERENCES locations(id), -- Specific location binding
    
    -- JSONB Logic
    conditions JSONB DEFAULT '{}'::jsonb,
    rewards JSONB DEFAULT '{}'::jsonb,
    flow_nodes JSONB DEFAULT '[]'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE scenarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read scenarios" ON scenarios FOR SELECT USING (true);
