-- Migration: Add hired count columns to user_profiles and create user_hire_events table for cron aggregation
-- Created At: 2026-07-08

-- 1. user_profiles テーブルへの累積雇用数カウンターカラム追加
ALTER TABLE public.user_profiles 
ADD COLUMN IF NOT EXISTS hired_shadow_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS hired_heroic_count INTEGER DEFAULT 0;

-- 2. user_hire_events (雇用ログ用テンポラリテーブル) の作成
CREATE TABLE IF NOT EXISTS public.user_hire_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_user_id UUID NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    origin_type TEXT NOT NULL, -- 'shadow_active' または 'shadow_heroic'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- インデックス作成 (パフォーマンス用)
CREATE INDEX IF NOT EXISTS idx_user_hire_events_source_user_id ON public.user_hire_events(source_user_id);

-- 3. 被雇用累積カウンターをアトミックに加算するデータベース関数 (RPC)
CREATE OR REPLACE FUNCTION public.increment_hired_counts(
    p_user_id UUID,
    p_shadow_inc INTEGER,
    p_heroic_inc INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.user_profiles
    SET 
        hired_shadow_count = COALESCE(hired_shadow_count, 0) + p_shadow_inc,
        hired_heroic_count = COALESCE(hired_heroic_count, 0) + p_heroic_inc
    WHERE id = p_user_id;
END;
$$;

-- 4. RLS の有効化 (API サーバー/Service Role のみで管理し、クライアントからの直接操作は全拒否)
ALTER TABLE public.user_hire_events ENABLE ROW LEVEL SECURITY;

-- PostgRESTスキーマキャッシュを再読み込み
NOTIFY pgrst, 'reload schema';
