ALTER TABLE items ADD COLUMN IF NOT EXISTS cost INTEGER DEFAULT 0;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS exp BIGINT DEFAULT 0;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS max_deck_cost INTEGER DEFAULT 10;
