-- Migration to fix colosseum reward pool schema and data
-- Created: 2026-06-23

-- 1. Add rarity column if not exists
ALTER TABLE public.colosseum_reward_pool ADD COLUMN IF NOT EXISTS rarity TEXT;

-- 2. Clear existing entries to avoid duplicates/legacy ids
TRUNCATE TABLE public.colosseum_reward_pool;

-- 3. Insert correct aligned entries from staging
INSERT INTO public.colosseum_reward_pool (reward_type, reward_id, name, rarity) VALUES
  ('item', '15', '傷薬 M', 'common'),
  ('item', '19', '解毒剤', 'common'),
  ('item', '191', '騎士の盾', 'rare'),
  ('item', '192', '白銀の槍', 'rare'),
  ('item', '194', '十字軍の指輪', 'rare'),
  ('item', '196', '錬金術セット', 'rare'),
  ('item', '197', '商人の鞄', 'rare'),
  ('item', '198', '砂漠の外套', 'super_rare'),
  ('item', '202', '呪符セット', 'rare'),
  ('item', '203', '当世具足', 'rare'),
  ('item', '205', '忍具入れ', 'rare'),
  ('item', '206', '神器:草薙(模造)', 'super_rare'),
  ('item', '208', '青龍偃月刀', 'super_rare'),
  ('item', '21', '火炎瓶', 'common'),
  ('item', '210', '鉄の爪', 'rare'),
  ('item', '214', '冒険者の靴', 'rare'),
  ('item', '219', '重装鎧', 'rare'),
  ('item', '22', '砥石', 'common'),
  ('item', '222', '幸運のコイン', 'rare'),
  ('item', '23', '煙玉', 'common'),
  ('item', '230', '大賢者の杖', 'super_rare'),
  ('item', '233', '黄金のサイコロ', 'rare'),
  ('item', '238', '般若の面', 'super_rare'),
  ('item', '244', '盗賊の七つ道具', 'rare'),
  ('item', '245', '旅人のリュック', 'rare'),
  ('item', '423', '天使の涙', 'super_rare'),
  ('item', '53', '応急処置キット', 'common'),
  ('item', 'item_black_market_elixir', '禁術の秘薬', 'super_rare'),
  ('item', 'item_desert_spice', '砂漠の香辛料', 'rare'),
  ('item', 'item_dragon_blood', '竜血', 'super_rare'),
  ('item', 'item_high_potion', '上級傷薬', 'rare'),
  ('item', 'item_karyu_tea', 'カリュウ茶', 'rare'),
  ('item', 'item_oasis_water', '聖都の霊水', 'rare'),
  ('item', 'item_roland_blessing', 'ローランの祝福', 'rare'),
  ('item', 'item_roland_elixir', 'ローランの霊薬', 'super_rare'),
  ('item', 'item_tent', 'テント', 'rare'),
  ('item', 'item_yato_poison', '夜刀の毒薬', 'rare'),
  ('item', 'item_yato_smoke', '夜刀の煙玉', 'rare'),
  ('skill', '3011', '教本:強打', 'rare'),
  ('skill', '3012', '教本:斬撃', 'common'),
  ('skill', '3013', '教本:突き', 'common'),
  ('skill', '3015', '教本:応急手当', 'common'),
  ('skill', '3018', '教本:クイックステップ', 'common'),
  ('skill', '3019', '教本:挑発', 'common'),
  ('skill', '3022', '巻物:裁き', 'rare'),
  ('skill', '3024', '聖書:治癒', 'rare'),
  ('skill', '3025', '巻物:聖壁', 'super_rare'),
  ('skill', '3035', '奥義書:居合切り', 'rare'),
  ('skill', '3037', '教本:龍の咆哮', 'rare'),
  ('skill', '3039', '奥義書:連撃', 'rare'),
  ('skill', '3047', '魔導書:メテオストライク', 'super_rare'),
  ('skill', '3050', '奥義書:暗殺', 'rare'),
  ('skill', '3053', '巻物:獅子の心', 'super_rare'),
  ('skill', '3055', '奥義書:岩砕き', 'super_rare'),
  ('skill', '3057', '禁書:闇の代償', 'super_rare'),
  ('skill', '3059', '禁薬:狂戦士の薬', 'super_rare'),
  ('skill', '3060', '禁書:魂の生贄', 'super_rare'),
  ('skill', '3061', '教本:調毒', 'rare'),
  ('skill', '3062', '禁術:血の契約書', 'rare'),
  ('skill', '3063', '教本:瞑想', 'common'),
  ('skill', '3065', '魔導書:火球', 'rare'),
  ('skill', '3066', '魔導書:氷槍', 'rare'),
  ('skill', '3067', '魔導書:雷撃', 'rare'),
  ('skill', '3088', '禁書:時止めの法', 'super_rare');
